### ISSUE TITLE
Minor Issues: Hide Script Box, Scripts have to be in the Script directory and not a subdirectory, verbose output as sideeffect in iPython

### ISSUE THREAD

**Issue by fmagin** [justfoxing/ghidra_bridge#1] opened 2019-04-08 19:57 UTC
System:
Arch Linux using the ghidra v9.0.1 package from the AUR ( https://aur.archlinux.org/packages/ghidra/)

I have various minor issues I am collecting here:

First:
I get a script box with the red dragon eating bits to indicate that a script is currently running. This is just mildly annoying because (unlike IDA...) the tool can still be used while a script is running. Maybe there is some other way to access the API, potentially via an Extension instead of script similar to how the Jython Shell accesses the API.

Second:
The doc states "Add the directory with the scripts in it to Ghidra's scripts directories." This did not work for me, the scripts had to be in the toplevel in my `ghidra_scripts` directory. I have no idea if this is a config issue on my side, a linux issue, or something else.

Third:
Using the plugin in an interactive shell like IPython generates a lot of output and makes it hard to see what the actual result of whatever was done should be. In IPython tab completion leads to this too.

**Comment by justfoxing** [comment] 2019-04-08 21:02
1) This is as intended, at least while ghidra_bridge is still under heavy dev. The dragon popup gives me/other users a confirmation/reminder that the bridge server is still running, and an easy way to kill it to load new changes without having to shutdown Ghidra. Best suggestion at this stage is just dragging the popup off to the side of the screen so it's not in your way when you're using the GUI.

I'll keep thinking about other options for this - if I can find a good way of running without the popup, it might make sense to have two start scripts, with/without the popup. 

2) This is a doco issue on me - I meant "add the path to the directory to the script directories field in the Script Manager", not copy the directory into your Ghidra scripts directory, but I totally see how you got that instead. My bad, I'll clean it up on my next runthrough. Long-term, aim is to look into how Ghidra plugins are packaged and use that instead.

3) I'm guessing this is being caused by all the logging cruft I've left in there - any time IPython's looking up methods or whatnot, that'd be firing off remote gets and calls. I'll make a commit today to comment out the logging, and aim to bring it back as something I can turn on/off easily for troubleshooting only.

**Comment by fmagin** [comment] 2019-04-09 08:04
3. My suggestion for the logging would be to use the Python logging module. https://docs.python.org/3/howto/logging.html
Then you can just set the logging level at some point (or for some module specifically) to get all the relevant info (or dump it somewhere else)

**Comment by justfoxing** [comment] 2019-04-10 08:21
Yup, that's the plan when I get enough cycles (commenting out was just the quick win). Closing now, based on 1) wontfix, 2) fixed, 3) issue fixed, enhancement forthcoming).

**Closed by justfoxing** 2019-04-10 08:21 UTC
